[package]
name = "barreleye"
description = "Open-source blockchain analytics."
repository = "https://github.com/barreleye/barreleye"
documentation = "https://docs.rs/barreleye"
homepage = "https://barreleye.com"
version = "0.2.0-alpha.0"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.75"
readme = "README.md"
keywords = ["blockchain", "cryptocurrency", "insights", "analytics", "kyc"]

[[bin]]
name = "barreleye"
path = "src/main.rs"

[workspace]
members = [ "common", "indexer", "server" ]

[package.metadata.cargo-udeps.ignore]
normal = ["color-eyre"]

[dependencies]
barreleye-common = { path = "./common", version = "0.2.0-alpha.0" }
barreleye-indexer = { path = "./indexer", version = "0.2.0-alpha.0" }
barreleye-server = { path = "./server", version = "0.2.0-alpha.0" }
log = "0.4.20"
color-eyre = "0.6.2"
eyre = "0.6.12"
dotenvy = "0.15.7"
chrono = { version = "0.4.33", default-features = false, features = ["clock", "std"] }
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
console = "0.15.8"
