[package]
name = "barreleye"
description = "Open-source blockchain KYC."
repository = "https://github.com/barreleye/barreleye"
documentation = "https://docs.rs/barreleye"
homepage = "https://barreleye.com"
version = "0.1.0"
license = "AGPL-3.0"
edition = "2021"
rust-version = "1.70"
readme = "README.md"
keywords = ["blockchain", "cryptocurrency", "insights", "analytics", "kyc"]

[[bin]]
name = "barreleye"
path = "src/main.rs"

[workspace]
members = [ "common", "indexer", "server" ]

[package.metadata.cargo-udeps.ignore]
normal = ["color-eyre"]

[dependencies]
log = "0.4.20"
color-eyre = "0.6.2"
eyre = "0.6.8"
dotenvy = "0.15.7"
chrono = { version = "0.4.30", default-features = false, features = ["clock", "std"] }
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
console = "0.15.7"

barreleye-common = { path = "./common", version = "0.1.0" }
barreleye-indexer = { path = "./indexer", version = "0.1.0" }
barreleye-server = { path = "./server", version = "0.1.0" }
