targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "warn"
unsound = "deny"
yanked = "deny"
notice = "warn"
ignore = [
    # @TODO dotenv is Unmaintained
    "RUSTSEC-2021-0141",
    # @TODO `libsqlite3-sys` via C SQLite CVE-2022-35737 (@TODO waiting for sqlx update)
    "RUSTSEC-2022-0090",
    # @TODO Ouroboros is Unsound
    "RUSTSEC-2023-0042"
]

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
copyleft = "deny"
default = "warn"
unused-allowed-license = "deny"
confidence-threshold = 0.95
allow = ["MPL-2.0", "MITNFA"]
exceptions = [
    { name = "barreleye", allow = ["AGPL-3.0"] },
    { name = "barreleye-common", allow = ["AGPL-3.0"] },
    { name = "barreleye-indexer", allow = ["AGPL-3.0"] },
    { name = "barreleye-server", allow = ["AGPL-3.0"] },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c }
]

[[licenses.clarify]]
name = "rustls-webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c }
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[bans]
multiple-versions = "allow"
wildcards = "deny"
highlight = "simplest-path"
skip-tree = []
