[graph]
all-features = true

[advisories]
version = 2
ignore = [
    # Marvin Attack: potential key recovery through timing sidechannels; https://rustsec.org/advisories/RUSTSEC-2023-0071
    "RUSTSEC-2023-0071",
    # Binary Protocol Misinterpretation caused by Truncating or Overflowing Casts; https://rustsec.org/advisories/RUSTSEC-2024-0363
    "RUSTSEC-2024-0363",
    # proc-macro-error is unmaintained; https://rustsec.org/advisories/RUSTSEC-2024-0370
    "RUSTSEC-2024-0370",
]

[licenses]
version = 2
allow = [
    "0BSD",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "MITNFA",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib",
    # https://github.com/briansmith/ring/issues/902
    "LicenseRef-ring",
    # https://github.com/rustls/webpki/blob/main/LICENSE ISC Style
    "LicenseRef-rustls-webpki",
]

exceptions = [
    { allow = ["MPL-2.0"], name = "option-ext" },
    { allow = ["MPL-2.0"], name = "webpki-roots" },
]

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
name = "rustls-webpki"
expression = "LicenseRef-rustls-webpki"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]

[bans]
multiple-versions = "allow"
wildcards = "deny"
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []